"""06 - Generate the verification checklist from the data.

The checklist is not written by hand. Every [VERIFY] item in it is enumerated
from envelope_overlap.csv, so the document cannot fall out of step with the
register it is meant to gate.
"""
import csv, json, os
from collections import defaultdict

OUT, DOCS = "data/processed", "docs"

NARRATIVE_POINTS = [
    ("V2", "API gravity to density conversion",
     "The certification envelope is stated in API gravity 32-37 degAPI. Density "
     "is derived as rho = 999.016 * 141.5 / (degAPI + 131.5), giving "
     "{cert_low}-{cert_high} kg/m3. Confirm the conversion, and that the 60 degF "
     "reference temperature convention is the right one to compare against "
     "commercial specs quoted at 15 degC."),
    ("V3", "The either/or reading of 40 CFR 1090.305(c)",
     "The register treats cetane index >= 40 and aromatics <= 35 vol% as "
     "ALTERNATIVE compliance paths, not joint requirements. If they are in fact "
     "joint, the market row for cetane_number and aromatics both change. Read "
     "1090.305(c) and rule."),
    ("V4", "Federal measurement of in-service diesel properties",
     "The register records federal_public_measurement = False for all "
     "{n_properties} properties. This rests on the reading that EPA's national "
     "fuels survey programme (40 CFR 1090 subpart O) is a gasoline programme and "
     "that EPA publishes gasoline fuel quality properties with no diesel "
     "equivalent. Confirm against 1090.1410 and 1090.1415 and EPA's fuel quality "
     "pages. If diesel IS sampled but unpublished, the gap class for those rows "
     "becomes sampled_unpublished, which is a materially different finding."),
    ("V5", "Five transcription spot checks",
     "Choose five rows of divergence_register.csv. For each, open the cited CFR "
     "provision in a browser and confirm the number in the register cell matches "
     "the regulation. Record which five, and the outcome, below."),
]


def main():
    os.makedirs(DOCS, exist_ok=True)
    stats = json.load(open(f"{OUT}/stats.json"))
    overlaps = list(csv.DictReader(open(f"{OUT}/envelope_overlap.csv")))
    unverified = [o for o in overlaps if o["std_verified"] == "False"]

    by_std = defaultdict(list)
    for o in unverified:
        by_std[o["standard"]].append(o)

    cert = stats["cert_density_kg_m3"]
    L = []
    A = L.append
    A("# FUELDIV — verification checklist\n")
    A("Generated by `scripts/06_docs.py`. Do not edit by hand; rerun the script.\n")
    A(f"Register: **{stats['n_properties']} properties**, "
      f"**{len(overlaps)} overlap rows**, "
      f"**{stats['n_unverified_commercial_values']} values requiring confirmation**.\n")
    A("Nothing in this project is published until every box below is ticked by "
      "the investigator personally. `scripts/07_publish_gate.py` refuses to "
      "release while any `[VERIFY]` tag remains in the tree.\n")
    A("---\n")
    A("## V1 — Commercial standard values (paywalled)\n")
    A("Each value below was entered into `scripts/02_register.py` from a "
      "consensus standard that is not freely available. Open the standard, "
      "confirm the number and the clause, then set `verified=True` on that "
      "`Envelope` and replace the `[VERIFY]` citation with the real clause "
      "reference.\n")
    A("**These include the EN 590 and EN 15940 density ranges already asserted "
      "in FACET's `PROGRAM.md`, which currently carry no citation in the "
      "programme repository.**\n")
    for std in sorted(by_std):
        A(f"\n### {std}\n")
        for o in sorted(by_std[std], key=lambda r: r["property"]):
            lo, hi = o["std_low"] or "—", o["std_high"] or "—"
            A(f"- [ ] `{o['property']}` = {lo} to {hi} {o['std_units']} "
              f"— {o['std_citation']}")
    A("\n---\n")
    for tag, title, body in NARRATIVE_POINTS:
        A(f"## {tag} — {title}\n")
        A("- [ ] " + body.format(cert_low=cert["low"], cert_high=cert["high"],
                                 n_properties=stats["n_properties"]) + "\n")
    A("---\n")
    A("## Reproduction\n")
    A("- [ ] `python3 src/fueldiv/properties.py` — all doctests pass")
    A("- [ ] `python3 scripts/02_register.py` — reproduces "
      f"{stats['n_properties']} properties and "
      f"{stats['n_disjoint_envelopes']} disjoint envelope(s)")
    pop = stats.get("population", {})
    if pop:
        A(f"- [ ] `python3 scripts/03_exposure.py` — reproduces "
          f"{pop['ci_families']:,} CI families, "
          f"{pop['volumetric_diesel_metering_families']:,} volumetric-metering")
    A("- [ ] Every figure regenerates from `data/processed/stats.json`")
    A("\n---\n")
    A("## Attestation\n")
    A("When every box above is ticked, and only then:\n")
    A("```bash\npython3 scripts/07_publish_gate.py --sign\n```\n")
    A("Signing asserts that you personally reproduced the pipeline and "
      "spot-checked its outputs against the primary sources. It is your name on "
      "the deposit.\n")

    path = f"{DOCS}/VERIFICATION_CHECKLIST.md"
    open(path, "w").write("\n".join(L) + "\n")
    print(f"wrote {path}")
    print(f"  {len(unverified)} [VERIFY] items across {len(by_std)} standards")
    print(f"  {len(NARRATIVE_POINTS)} narrative verification points")


if __name__ == "__main__":
    main()
